{
  parserClass="com.chm.plugin.idea.forestx.template.grammar.TemplateParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ForestTemplate"
  psiImplClassSuffix="Impl"
  psiPackage="com.chm.plugin.idea.forestx.template.psi"
  psiImplPackage="com.chm.plugin.idea.forestx.template.psi.impl"

  elementTypeHolderClass="com.chm.plugin.idea.forestx.template.psi.TemplateTypes"
  elementTypeClass="com.chm.plugin.idea.forestx.template.psi.ForestTemplateElementType"
  tokenTypeClass="com.chm.plugin.idea.forestx.template.psi.ForestTemplateTokenType"
}

StringTemplate ::= FT_DQ FT_JSTRING? StringBlockContent* FT_DQ

StringBlockContent ::= (PropertyBlock | ElBlock) FT_JSTRING?

PropertyBlock ::= PROP_BLOCK_BEGIN PropertyExpress PROP_BLOCK_END

ElBlock ::= EL_BLOCK_BEGIN ElExpress EL_BLOCK_END

ElExpress ::= Identity | Number

Number ::= EL_INT | EL_DECIMAL

Identity ::= EL_IDENTITY

PropertyExpress ::= PROP_NAME_PART (PROP_DOT PROP_NAME_PART)*

